-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 22:35:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treinador` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Treinadorcol` VARCHAR(45) NULL,
  `Equipe_ID_Equipe` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Treinador_Equipe_idx` (`Equipe_ID_Equipe` ASC) VISIBLE,
  CONSTRAINT `fk_Treinador_Equipe`
    FOREIGN KEY (`Equipe_ID_Equipe`)
    REFERENCES `mydb`.`Equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokedex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokedex` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Treinador_ID_Treinador` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Pokedex_Treinador1_idx` (`Treinador_ID_Treinador` ASC) VISIBLE,
  CONSTRAINT `fk_Pokedex_Treinador1`
    FOREIGN KEY (`Treinador_ID_Treinador`)
    REFERENCES `mydb`.`Treinador` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokemano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokemano` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokemano_has_Pokedex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokemano_has_Pokedex` (
  `Pokemano_ID` INT NOT NULL,
  `Pokedex_ID` INT NOT NULL,
  PRIMARY KEY (`Pokemano_ID`, `Pokedex_ID`),
  INDEX `fk_Pokemano_has_Pokedex_Pokedex1_idx` (`Pokedex_ID` ASC) VISIBLE,
  INDEX `fk_Pokemano_has_Pokedex_Pokemano1_idx` (`Pokemano_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pokemano_has_Pokedex_Pokemano1`
    FOREIGN KEY (`Pokemano_ID`)
    REFERENCES `mydb`.`Pokemano` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemano_has_Pokedex_Pokedex1`
    FOREIGN KEY (`Pokedex_ID`)
    REFERENCES `mydb`.`Pokedex` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habilidade` (
  `idHabilidade` INT NOT NULL,
  `Dano` INT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Tipo de Dano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHabilidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokemano_has_Habilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokemano_has_Habilidade` (
  `Pokemano_ID` INT NOT NULL,
  `Habilidade_idHabilidade` INT NOT NULL,
  PRIMARY KEY (`Pokemano_ID`, `Habilidade_idHabilidade`),
  INDEX `fk_Pokemano_has_Habilidade_Habilidade1_idx` (`Habilidade_idHabilidade` ASC) VISIBLE,
  INDEX `fk_Pokemano_has_Habilidade_Pokemano1_idx` (`Pokemano_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Pokemano_has_Habilidade_Pokemano1`
    FOREIGN KEY (`Pokemano_ID`)
    REFERENCES `mydb`.`Pokemano` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemano_has_Habilidade_Habilidade1`
    FOREIGN KEY (`Habilidade_idHabilidade`)
    REFERENCES `mydb`.`Habilidade` (`idHabilidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
